name: Deploy via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'
        extensions: mbstring, bcmath
        
    - name: Install PHP Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --no-dev --optimize-autoloader --ignore-platform-reqs

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '22'
        
    - name: Install Node Dependencies & Build
      run: |
        npm install
        npm run build

    - name: Create Production .env
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
      run: |
        cp .env.example .env
        sed -i 's/APP_ENV=local/APP_ENV=production/' .env
        sed -i 's/APP_DEBUG=true/APP_DEBUG=false/' .env
        sed -i "s|APP_URL=http://localhost|APP_URL=http://${FTP_SERVER}|" .env
        sed -i 's/DB_CONNECTION=sqlite/DB_CONNECTION=mysql/' .env
        sed -i 's/DB_HOST=127.0.0.1/DB_HOST=db-a255f7a8-4b09-4119-88cc-67d68377c0fe.ap-northeast-1.public.db.laravel.cloud/' .env
        sed -i 's/DB_PORT=3306/DB_PORT=3306/' .env
        sed -i 's/DB_DATABASE=laravel/DB_DATABASE=gov/' .env
        sed -i 's/DB_USERNAME=root/DB_USERNAME=pw4hsxlm0kesnqpl/' .env
        sed -i 's/DB_PASSWORD=/DB_PASSWORD=SZA7Y2WWgQHbk3xMRmXi/' .env
        php artisan key:generate


